VERBOSE = 1
PULP_APP = test
PULP_APP_SRCS = main.c programFPGA.c fll.c
PULP_CFLAGS = -g
include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

data1: data1.h
	cp data1.h data.h
	touch main.c

data2: data2.h
	cp data2.h data.h
	touch main.c

data3: data3.h
	cp data3.h data.h
	touch main.c

data4: data4.h
	cp data4.h data.h
	touch main.c

data5: data5.h
	cp data5.h data.h
	touch main.c

data6: data6.h
	cp data6.h data.h
	touch main.c

data7: data7.h
	cp data7.h data.h
	touch main.c

data8: data8.h
	cp data8.h data.h
	touch main.c

data9: data9.h
	cp data9.h data.h
	touch main.c

data10: data10.h
	cp data10.h data.h
	touch main.c

data11: data11.h
	cp data11.h data.h
	touch main.c

data12: data12.h
	cp data12.h data.h
	touch main.c

data13: data13.h
	cp data13.h data.h
	touch main.c

